version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://devuser:devpass@db:5432/bhiv"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: bhiv
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: